package com.lovecoding.pojo;

import java.io.Serializable;

public class BaseDict implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_id
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_type_code
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_type_name
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_item_name
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_item_code
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictItemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_sort
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private Integer dictSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_enable
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_memo
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private String dictMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_dict
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_id
     *
     * @return the value of base_dict.dict_id
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_id
     *
     * @param dictId the value for base_dict.dict_id
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictId(String dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_type_code
     *
     * @return the value of base_dict.dict_type_code
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictTypeCode() {
        return dictTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_type_code
     *
     * @param dictTypeCode the value for base_dict.dict_type_code
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictTypeCode(String dictTypeCode) {
        this.dictTypeCode = dictTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_type_name
     *
     * @return the value of base_dict.dict_type_name
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictTypeName() {
        return dictTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_type_name
     *
     * @param dictTypeName the value for base_dict.dict_type_name
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictTypeName(String dictTypeName) {
        this.dictTypeName = dictTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_item_name
     *
     * @return the value of base_dict.dict_item_name
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictItemName() {
        return dictItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_item_name
     *
     * @param dictItemName the value for base_dict.dict_item_name
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictItemName(String dictItemName) {
        this.dictItemName = dictItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_item_code
     *
     * @return the value of base_dict.dict_item_code
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictItemCode() {
        return dictItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_item_code
     *
     * @param dictItemCode the value for base_dict.dict_item_code
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictItemCode(String dictItemCode) {
        this.dictItemCode = dictItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_sort
     *
     * @return the value of base_dict.dict_sort
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_sort
     *
     * @param dictSort the value for base_dict.dict_sort
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_enable
     *
     * @return the value of base_dict.dict_enable
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictEnable() {
        return dictEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_enable
     *
     * @param dictEnable the value for base_dict.dict_enable
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictEnable(String dictEnable) {
        this.dictEnable = dictEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_memo
     *
     * @return the value of base_dict.dict_memo
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public String getDictMemo() {
        return dictMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_memo
     *
     * @param dictMemo the value for base_dict.dict_memo
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    public void setDictMemo(String dictMemo) {
        this.dictMemo = dictMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbg.generated Fri Aug 06 16:28:02 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictId=").append(dictId);
        sb.append(", dictTypeCode=").append(dictTypeCode);
        sb.append(", dictTypeName=").append(dictTypeName);
        sb.append(", dictItemName=").append(dictItemName);
        sb.append(", dictItemCode=").append(dictItemCode);
        sb.append(", dictSort=").append(dictSort);
        sb.append(", dictEnable=").append(dictEnable);
        sb.append(", dictMemo=").append(dictMemo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}